# install.packages("msigdbr")
# install.packages("ggupset")
install.packages("ashr")
install.packages("Rcpp")
install.packages("ggpubr")
# install.packages("UpSetR")
# BiocManager::install("EnhancedVolcano")
shhh <- suppressPackageStartupMessages
shhh(library("dearseq"))
shhh(library("DESeq2"))
shhh(library("vsn"))
shhh(library("ggfortify"))
shhh(library("ggplot2"))
shhh(library("genefilter"))
shhh(library("pheatmap"))
shhh(library("repr"))
shhh(library("purrr"))
shhh(library("stringr"))
shhh(library("hexbin"))
shhh(library("EnsDb.Mmusculus.v79"))
shhh(library("dplyr"))
shhh(library("msigdbr"))
shhh(library("clusterProfiler"))
shhh(library("enrichplot"))
shhh(library("EnhancedVolcano"))
shhh(library("ggpubr"))
# shhh(library("gaospecial/ggVennDiagram"))

edb <- EnsDb.Mmusculus.v79
